# license_template_path = ""
# required_version = "array_width = 80
attr_fn_like_width = 80
binop_separator = "Back"
blank_lines_lower_bound = 1
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
chain_width = 80
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
doc_comment_code_block_width = 80
edition = "2021"
empty_item_single_line = true
enum_discrim_align_threshold = 20
error_on_line_overflow = true
error_on_unformatted = true
fn_call_width = 80
fn_params_layout = "Tall"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = false
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = false
hex_literal_case = "Upper"
hide_parse_errors = false
imports_granularity = "One"
imports_indent = "Visual"
imports_layout = "Mixed"
indent_style = "Visual"
inline_attribute_width = 80
match_arm_blocks = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 80
merge_derives = true
newline_style = "Native"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
report_fixme = "Always"
report_todo = true
short_array_element_width_threshold = 80
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 20
struct_lit_single_line = true
struct_lit_width = 80
struct_variant_width = 80
tab_spaces = 2
trailing_comma = "Always"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
version = "Two"
where_single_line = false
wrap_comments = true